import { useQuery } from "@tanstack/react-query";
import type { Plugin } from "chart.js";
import { Line } from "react-chartjs-2";
import { useTheme } from "@mui/material/styles";
import dayjs from "dayjs";
import { ComponentProps } from "react";
import { repoDlProxy } from "../../repo/repoDlProxy";
import { Box } from "@mui/system";
import ApiRequestAdapter from "../../adapters/apiRequestAdapter";

interface IWatchlistChartProps {
  stockId: string;
}

let lastTouchTime = 0;

const clearTouchPlugin: Plugin<"line"> = {
  id: "clearTouchPlugin",
  beforeEvent(_chart, args) {
    const event = args.event;
    const nativeEvent = event.native;
    const type: string = event.type;

    // Check if the event is a native touch or pointer-touch event
    const isTouch =
      type.startsWith("touch") ||
      (nativeEvent !== null &&
        "pointerType" in nativeEvent &&
        nativeEvent.pointerType === "touch");

    if (isTouch) {
      lastTouchTime = Date.now();
    }

    // BLOCK synthetic mousemove/pointermove events generated by the browser shortly after a tap
    if (
      (type === "mousemove" || type === "pointermove") &&
      !isTouch &&
      Date.now() - lastTouchTime < 500
    ) {
      return false; // Tells Chart.js to completely ignore this ghost mouse move
    }
  },
  afterEvent(chart, args) {
    const type: string = args.event.type;
    if (
      ["touchend", "touchcancel", "pointerup", "pointerleave", "mouseleave"].includes(
        type,
      )
    ) {
      // Clear tooltip after synthetic event queue clears
      setTimeout(() => {
        chart.setActiveElements([]);
        if (chart.tooltip) {
          chart.tooltip.setActiveElements([], { x: 0, y: 0 });
        }
        chart.update();
      }, 50);
    }
  },
};

export default function WatchlistChart({ stockId }: IWatchlistChartProps) {
  const theme = useTheme();
  const qry = useQuery(ApiRequestAdapter.queryOptions(repoDlProxy.Get({ stockId })));

  if (qry.isError || !qry.data) {
    return <></>;
  }

  const chartData = qry.data;
  const prevClosePrice: number =
    chartData.spark.result[0].response[0].meta.previousClose;
  const curTradeTimestamps: number[] = Array.from(
    chartData.spark.result[0].response[0].timestamp,
  ); // Shadow copy of a React State before mutation
  const curTradePrices = Array.from(
    chartData.spark.result[0].response[0].indicators.quote[0].close,
  ).filter((price): price is number => price !== null); // Shadow copy of a React State
  //const tsTradeStart = qry.data.spark.result[0].response[0].meta.currentTradingPeriod.regular.start;
  const tsTradeStart: number =
    chartData.spark.result[0].response[0].meta.currentTradingPeriod.regular
      .start;
  const tsTradeEnd: number =
    chartData.spark.result[0].response[0].meta.currentTradingPeriod.regular.end;
  const secondPerTick = 5 * 60; //300
  //const totalTicksCnt = Math.floor((tsTradeEnd - tsTradeStart) / secondPerTick)

  const options_min: ComponentProps<typeof Line>["options"] = {
    events: [
      "mousemove",
      "mouseout",
      "touchstart",
      "touchmove",
      "touchend",
      "touchcancel",
      "pointerdown",
      "pointermove",
      "pointerup",
      "pointerleave",
      "pointercancel",
    ],
    animation: false,
    responsive: true,
    maintainAspectRatio: false,
    layout: {
      padding: 0,
    },
    elements: {
      point: {
        hitRadius: 1,
      },
    },
    scales: {
      x: {
        display: false,
      },
      y: {
        min:
          Math.min(
            ...curTradePrices.filter((price) => price !== null),
            prevClosePrice,
          ) * 0.999,
        max:
          Math.max(
            ...curTradePrices.filter((price) => price !== null),
            prevClosePrice,
          ) * 1.001,
        ticks: {
          callback: function (val, _index, _values) {
            const num = typeof val === "number" ? val : Number(val);
            return num.toFixed(2);
          },
          font: {
            size: 9,
          },
        },
        afterBuildTicks: (axis) =>
          (axis.ticks = [prevClosePrice].map((v) => ({ value: v }))),
      },
    },
    interaction: {
      intersect: false,
      mode: "index",
      axis: "x",
    },
    plugins: {
      legend: {
        display: false,
      },
      tooltip: {
        filter: (tooltipItem) => tooltipItem.datasetIndex === 0,
        yAlign: "center", // Moves tooltip to the side of the cursor
        caretPadding: 15, // Adds spacing from the cursor
      },
    },
  };

  let processingTradeTimestamp =
    curTradeTimestamps[curTradeTimestamps.length - 1];
  while (
    processingTradeTimestamp < tsTradeEnd &&
    processingTradeTimestamp >= tsTradeStart
  ) {
    processingTradeTimestamp += secondPerTick;
    curTradeTimestamps.push(processingTradeTimestamp);
  }

  return (
    <Box
      sx={{
        position: "relative",
        height: "3em",
        width: { xs: "9em", sm: "11em", lg: "15em" },
      }}
    >
      {chartData && (
        <Box //Hacky way to expand the canvas a little bit more
          sx={{
            position: "absolute",
            top: "-0.3em",   // Shifts canvas upward
            left: 0,
            height: "3.5em",   // Expanded height (larger than parent's 3em)
            width: "100%",   // Can also be expanded (e.g., "120%")
          }}
        >
          <Line
            options={options_min}
            plugins={[clearTouchPlugin]}
            data={{
              labels: curTradeTimestamps.map((timestamp) =>
                dayjs.unix(timestamp).format("MM-DD HH:mm"),
              ),
              datasets: [
                {
                  data: curTradePrices,
                  borderWidth: 1.1,
                  pointRadius: 0,

                  // Mouse hover legend color
                  pointBackgroundColor: (ctx) => {
                    const price = ctx.parsed.y;

                    if (price == null) {
                      return undefined;
                    }

                    return price >= prevClosePrice
                      ? theme.deltaColor.up.color
                      : theme.deltaColor.down.color;
                  },

                  // Line color
                  segment: {
                    borderColor: (ctx) => {
                      const p0 = ctx.p0.parsed.y;
                      const p1 = ctx.p1.parsed.y;

                      if (p0 == null || p1 == null) {
                        return undefined;
                      }

                      return p0 >= prevClosePrice && p1 >= prevClosePrice
                        ? theme.deltaColor.up.color
                        : theme.deltaColor.down.color;
                    },
                  },
                },
                {
                  fill: false,
                  backgroundColor: theme.chartGreyLine.color,
                  borderColor: theme.chartGreyLine.color,
                  borderDash: [5, 5],
                  borderWidth: 0.3,
                  pointRadius: 0,
                  pointHoverRadius: 0,
                  data: Array(curTradeTimestamps.length).fill(prevClosePrice),
                },
              ],
            }}
          ></Line>
        </Box>
      )}
    </Box>
  );
}
