import type { ChartOptions, Plugin } from "chart.js";

// Shared touch handling for Chart.js charts (extracted from the WatchlistChart fix).
// On mobile devices the tooltip gets stuck after a tap: Chart.js keeps the last
// active element because touchend/pointerup alone does not clear it, and the
// browser then fires synthetic mousemove/pointermove events that re-trigger the
// tooltip even though the finger has left the screen. The plugin below records
// real touch input, ignores those ghost mouse moves for a short window, and
// clears the tooltip once the touch sequence ends. The events list enables the
// touch/pointer lifecycle events Chart.js needs to observe for this to work.
// Reuse this helper instead of copying the plugin into each chart component.

// How long after a real touch to ignore synthetic mouse moves.
export const touchGhostWindowMs = 500;
// Delay before clearing, so the pending synthetic event queue can drain first.
export const touchClearDelayMs = 50;

// Touch/pointer lifecycle end events that should dismiss the tooltip.
export const touchEndEventTypes = [
  "touchend",
  "touchcancel",
  "pointerup",
  "pointerleave",
  "mouseleave",
];

// Chart.js events each chart must listen to for the plugin to see the full touch lifecycle.
export const touchSafeChartEvents: NonNullable<ChartOptions["events"]> = [
  "mousemove",
  "mouseout",
  "touchstart",
  "touchmove",
  "touchend",
  "touchcancel",
  "pointerdown",
  "pointermove",
  "pointerup",
  "pointerleave",
  "pointercancel",
];

// Creates an isolated clear-touch plugin instance per chart, so lastTouchTime
// is not shared across charts.
export function createClearTouchPlugin(): Plugin {
  let lastTouchTime = 0;

  return {
    id: "clearTouchPlugin",
    beforeEvent(_chart, args) {
      const event = args.event;
      const nativeEvent = event.native as {
        pointerType?: string;
      } | null;
      const type: string = event.type;

      // Check if the event is a native touch or pointer-touch event
      const isTouch =
        type.startsWith("touch") ||
        (nativeEvent !== null &&
          nativeEvent !== undefined &&
          "pointerType" in nativeEvent &&
          nativeEvent.pointerType === "touch");

      if (isTouch) {
        lastTouchTime = Date.now();
      }

      // BLOCK synthetic mousemove/pointermove events generated by the browser shortly after a tap
      if (
        (type === "mousemove" || type === "pointermove") &&
        !isTouch &&
        Date.now() - lastTouchTime < touchGhostWindowMs
      ) {
        return false; // Tells Chart.js to completely ignore this ghost mouse move
      }
    },
    afterEvent(chart, args) {
      const type: string = args.event.type;
      if ((touchEndEventTypes as string[]).includes(type)) {
        // Clear tooltip after synthetic event queue clears
        setTimeout(() => {
          chart.setActiveElements([]);
          if (chart.tooltip) {
            chart.tooltip.setActiveElements([], { x: 0, y: 0 });
          }
          chart.update();
        }, touchClearDelayMs);
      }
    },
  };
}
